language: go

go:
    - 1.4
    - tip

os:
    - linux
    - osx

env:
    - secure: "l04PdBqGjY+ZyC2ahT3bxbwWaE7Y2mjq4Ps6B8kSKRNMqW3H02POkLIcbgVqTtQsfVRYRT2vZTsgPHloXRT3VxpqpVpFx+AlOfWc+SPFuMmEIi+xIgqYegGZljxwVTHif+IzTYhcpXE+IxBcl58+iOPhAw+u5VnsQu3g0Ywg2N8="

script:
    - go get golang.org/x/tools/cmd/cover
    - go test -v -cover --benchmem --bench=. ./...
