language: go

go:
    - 1.4
    - tip

os:
    - linux
    - osx

before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

script:
    - go test -v -cover --benchmem --bench=. ./...
    - sh ./goclean.sh
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
