language: go

go:
    - 1.6
    - 1.6.1
    - 1.6.2
    - 1.6.3
    - 1.7
    - 1.7.1
    - tip

before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get golang.org/x/tools/cmd/goimports
    - go get github.com/golang/lint/golint
    - go get github.com/mattn/goveralls

script:
    - sh ./goclean.sh
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.cov -service=travis-ci
    - bash <(curl -s https://codecov.io/bash)
    - go test -bench=. -benchmem ./tradingdays
    - go test -bench=. -benchmem ./twse
    - go test -bench=. -benchmem ./utils
    - sh ./install_all_cmd.sh
